name: histomil
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - git
  - pip:
    - git+https://github.com/GabrielCabas/MIL-Lab.git@bug_attention_returned_false #Replace it with original when the PR is merged
    - git+https://github.com/oval-group/smooth-topk.git # Required for CLAM
    - seaborn
    - matplotlib
    - pytest